# -*- coding: utf-8 -*-
"""xp gold

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kaC0CjJUtZwTDI9tks1Nit5BfbUrtxnu

Instructions
Create a new notebook in Google Colab.
Write a Python script to check if a given number is a prime number. For example, check if the number 7 is prime.
"""

def is_prime(number):
    """
    Checks if a given number is a prime number.

    Args:
        number: The number to check.

    Returns:
        True if the number is prime, False otherwise.
    """

    # Prime numbers are greater than 1
    if number <= 1:
        return False

    # 2 is the only even prime number
    if number <= 3:
        return True

    # Check if the number is divisible by 2 or 3
    if number % 2 == 0 or number % 3 == 0:
        return False

    i = 5
    while i * i <= number:
        if number % i == 0 or number % (i + 2) == 0:
            return False
        i += 6

    return True

# Example usage:
number_to_check = 7
if is_prime(number_to_check):
    print(f"{number_to_check} is a prime number.")
else:
    print(f"{number_to_check} is not a prime number.")

"""
Exercise 2: List Comprehensions with Jupyter Notebook.
Instructions
Launch Jupyter Notebook on your local machine.
Create a new notebook.
Write a Python script using list comprehensions to find all numbers in a given range (e.g., 1 to 20) that are divisible by a specific number (e.g., 3).
"""

divisible_by_5 = [num for num in range(1, 21) if num % 5 == 0]
divisible_by_5

"""Exercise 3: Kaggle Dataset Exploration: Print Dataset Information
Instructions
Choose a dataset other than Titanic from Kaggle (e.g., Iris Dataset).
Write a script to print the head, columns, and data types of the chosen dataset (either on Google Colab or Jupyter notebook)

"""

!pip install kaggle
from google.colab import files
files.upload()

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d uciml/iris

!unzip iris.zip

import pandas as pd

# Load the Iris dataset
data = pd.read_csv('Iris.csv')

# Print the first 5 rows of the dataset
print("Head of the dataset:\n")
print(data.head())

# Print the column names of the dataset
print("\nColumns of the dataset:\n")
print(data.columns)

# Print the data types of each column
print("\nData types of the dataset:\n")
data.dtypes

"""Exercise 4: Basic Data Analysis with Kaggle
Instructions
Select a simple dataset from Kaggle (e.g., Boston Housing Dataset).
Perform basic data analysis to find the mean, median, and standard deviation of a particular column.

"""

import pandas as pd

data = pd.read_csv('Iris.csv')

sepal_length_mean = data['SepalLengthCm'].mean()
sepal_length_median = data['SepalLengthCm'].median()
sepal_length_std = data['SepalLengthCm'].std()

print(f"Mean of SepalLengthCm: {sepal_length_mean}")
print(f"Median of SepalLengthCm: {sepal_length_median}")
print(f"Standard Deviation of SepalLengthCm: {sepal_length_std}")

"""Exercise 5: Transforming Qualitative Data into Quantitative Data with the Titanic Dataset
Instructions
Download the Titanic dataset from a source like Kaggle.
Load the dataset into a Python environment using Pandas.
Transform the sex column, to represent 0 as ‘female’ and 1 for ‘male’ using .map function.

"""

import pandas as pd
!kaggle datasets download -d heptapod/titanic

!unzip titanic.zip

titanic = pd.read_csv('titanic.csv')

titanic['Sex'] = titanic['Sex'].map({'female': 0, 'male': 1})

print(titanic['Sex'].head())