# -*- coding: utf-8 -*-
"""daily challenge

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HUcalJHr0LxZXfHLyNBBUWK5Ac7lqf3E

Your Task
For this challenge, please use google colab.

Load and Visualize Images using the Flower Color Images dataset



from google.colab import files
files.upload()

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d olgabelitskaya/flower-color-images


!unzip flower-color-images.zip


Install the libraries :
!pip install tensorflow
! pip install keras
! pip install pillow


To load an image and display it :
# Load an image using PIL
image_path = 'flowers/flowers/19_010.png'
original_image = Image.open(image_path)

# Display the original image using matplotlib
plt.imshow(original_image)


Rotate an image by 90 degrees
from scipy.ndimage import rotate
def rotate_image_30_degrees(image):
return rotate( , , , ) #complete it


Flip an image horizontally and then vertically using mirror and flip functions from ImageOps
Zoom in on an image (scale by 1.2x) using .resize(...)
"""

import matplotlib.pyplot as plt
from PIL import Image, ImageOps
from scipy.ndimage import rotate
import os

# Assuming the 'flowers' directory is in the current working directory
image_path = 'flowers/flowers/19_010.png'

if os.path.exists(image_path):
  # Load an image using PIL
  original_image = Image.open(image_path)

  # Display the original image using matplotlib
  plt.figure(figsize=(8, 6))  # Adjust figure size for better visualization
  plt.imshow(original_image)
  plt.title("Original Image")
  plt.axis('off')
  plt.show()

  # Rotate an image by 30 degrees
  rotated_image = rotate(original_image, angle=30, reshape=False) # reshape = False to avoid image shrinking
  plt.figure(figsize=(8, 6))
  plt.imshow(rotated_image)
  plt.title("Rotated Image")
  plt.axis('off')
  plt.show()


  # Flip an image horizontally and then vertically
  horizontally_flipped_image = ImageOps.mirror(original_image)
  vertically_flipped_image = ImageOps.flip(horizontally_flipped_image)

  plt.figure(figsize=(8, 6))
  plt.imshow(vertically_flipped_image)
  plt.title("Flipped Image")
  plt.axis('off')
  plt.show()

  # Zoom in on an image (scale by 1.2x)
  width, height = original_image.size
  new_width = int(width * 1.2)
  new_height = int(height * 1.2)
  zoomed_image = original_image.resize((new_width, new_height))

  plt.figure(figsize=(8, 6))
  plt.imshow(zoomed_image)
  plt.title("Zoomed Image")
  plt.axis('off')
  plt.show()

else:
  print(f"Error: Image file not found at {image_path}")