# -*- coding: utf-8 -*-
"""daily challenge

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fqQf7GbNjPWmWh1HFshGaE7H6jt-iMZp

Instructions
Challenge 1
Ask the user for a number and a length.
Create a program that prints a list of multiples of the number until the list length reaches length.
Examples

number: 7 - length 5 ➞ [7, 14, 21, 28, 35]

number: 12 - length 10 ➞ [12, 24, 36, 48, 60, 72, 84, 96, 108, 120]

number: 17 - length 6 ➞ [17, 34, 51, 68, 85, 102]
"""

def multiples_list(number, length):
    multiples = []
    current_multiple = number
    for _ in range(length):
        multiples.append(current_multiple)
        current_multiple += number
    return multiples

if __name__ == "__main__":
    try:
      number = int(input("Enter a number: "))
      length = int(input("Enter the desired length of the list: "))
      result = multiples_list(number, length)
      print(result)
    except ValueError:
      print("Invalid input. Please enter integers for number and length.")

"""Challenge 2
Write a program that asks a string to the user, and display a new string with any duplicate consecutive letters removed.
Examples

user's word : "ppoeemm" ➞ "poem"

user's word : "wiiiinnnnd" ➞ "wind"

user's word : "ttiiitllleeee" ➞ "title"

user's word : "cccccaaarrrbbonnnnn" ➞ "carbon"
Notes
Final strings won’t include words with double letters (e.g. “passing”, “lottery”).


"""

def remove_consecutive_duplicates(word):
    if not word:
        return ""

    new_word = [word[0]]
    for i in range(1, len(word)):
        if word[i] != word[i-1]:
            new_word.append(word[i])
    return "".join(new_word)

if __name__ == "__main__":
    user_word = input("Enter a word: ")
    result = remove_consecutive_duplicates(user_word)
result