# -*- coding: utf-8 -*-
"""xp

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rw_T4YOpayBRV9nvS-EPdmpE2wIRhDbN

Exercise 1 : Favorite Numbers
Instructions
Create a set called my_fav_numbers with all your favorites numbers.
Add two new numbers to the set.
Remove the last number.
Create a set called friend_fav_numbers with your friend’s favorites numbers.
Concatenate my_fav_numbers and friend_fav_numbers to a new variable called our_fav_numbers.
"""

my_fav_number={1,2,3,4,5}
my_fav_number.add(6)
my_fav_number.add(7)
my_fav_number.remove(7)
friend_fav_numbers={8,9,10}
our_fav_numbers=my_fav_number.union(friend_fav_numbers)
print(our_fav_numbers)

"""Exercise 2: Tuple
Instructions
Given a tuple which value is integers, is it possible to add more integers to the tuple?

no tubles are immutable

Exercise 3: List
Instructions
Using this list basket = ["Banana", "Apples", "Oranges", "Blueberries"];

Remove “Banana” from the list.
Remove “Blueberries” from the list.
Add “Kiwi” to the end of the list.
Add “Apples” to the beginning of the list.
Count how many apples are in the basket.
Empty the basket.
Print(basket)
"""

basket = ["Banana", "Apples", "Oranges", "Blueberries"]
basket.remove("Banana")
basket.remove("Blueberries")
basket.append("Kiwi")
basket.insert(0,"Apples")
print(basket.count("Apples"))
basket.clear()
print(basket)

"""🌟 Exercise 4: Floats
Instructions
Recap – What is a float? What is the difference between an integer and a float?
Create a list containing the following sequence of floats and integers (it should be a list with mixed types): 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5 (don’t hard-code the sequence).
Can you think of another way to generate a sequence of floats?

 a float is not a round number its  0.5 0.6 4.5  integers are round numbers like
5 7 11 25
"""

numbers=[1.5,2,2.5,3,3.5,4,4.5]
float_list = [i + 0.5 for i in range(1, 9) if i != 8]
float_list

""" Exercise 5: For Loop
Instructions
Use a for loop to print all numbers from 1 to 20, inclusive.
Using a for loop, that loops from 1 to 20(inclusive), print out every element which has an even index.

"""

for i in range(1,20):
  print(i)
for i in range(1,20):
  if i%2==0:
    print(i)

"""
🌟 Exercise 6 : While Loop
Instructions
Write a while loop that will continuously ask the user for their name, unless the input is equal to your name.

"""

user_name=input('whats youre name')
name='tarek'
while user_name.lower()!=name:
  user_name=input('whats youre name')

""" Exercise 7: Favorite fruits
Instructions
Ask the user to input their favorite fruit(s) (one or several fruits).
Hint : Use the built in input method. Ask the user to separate the fruits with a single space, eg. "apple mango cherry".
Store the favorite fruit(s) in a list (convert the string of words into a list of words).
Now that we have a list of fruits, ask the user to input a name of any fruit.
If the user’s input is in the favorite fruits list, print “You chose one of your favorite fruits! Enjoy!”.
If the user’s input is NOT in the list, print, “You chose a new fruit. I hope you enjoy”.

"""

fav_fruits=input('whats youre fav fruits one or several')
list_of_fruits=fav_fruits.split()
user_input=input('input a name of any fruit')
if user_input in list_of_fruits:
  print('You chose one of your favorite fruits! Enjoy!')

"""Exercise 8: Who ordered a pizza ?
Instructions
Write a loop that asks a user to enter a series of pizza toppings, when the user inputs ‘quit’ stop asking for toppings.
As they enter each topping, print a message saying you’ll add that topping to their pizza.
Upon exiting the loop print all the toppings on the pizza pie and what the total price is (10 + 2.5 for each topping).

"""

toppings = []
price = 10

while True:
  topping = input("Enter a pizza topping (or type 'quit' to finish): ")
  if topping.lower() == 'quit':
    break
  else:
    toppings.append(topping)
    price += 2.5
    print(f"I'll add {topping} to your pizza.")

print("\nYour pizza will have:")
for topping in toppings:
  print(topping)
print(f"Total price: ${price}")

"""
Exercise 9: Cinemax
Instructions
A movie theater charges different ticket prices depending on a person’s age.
if a person is under the age of 3, the ticket is free.
if they are between 3 and 12, the ticket is $10.
if they are over the age of 12, the ticket is $15.

Ask a family the age of each person who wants a ticket.

Store the total cost of all the family’s tickets and print it out.

A group of teenagers are coming to your movie theater and want to watch a movie that is restricted for people between the ages of 16 and 21.
Given a list of names, write a program that asks teenager for their age, if they are not permitted to watch the movie, remove them from the list.
At the end, print the final list.
"""

total_cost = 0
while True:
    try:
        age = int(input("Enter the age of the person (or enter a negative number to finish): "))
        if age < 0:
            break
        elif age < 3:
            cost = 0
        elif 3 <= age <= 12:
            cost = 10
        else:
            cost = 15
        total_cost += cost
        print(f"The ticket cost for this person is ${cost}")
    except ValueError:
        print("Invalid input. Please enter a valid age (a whole number).")

print(f"The total cost for the family's tickets is ${total_cost}")

teenagers = ["Alice", "Bob", "Charlie", "David", "Eve"]
permitted_teenagers = []

for teenager in teenagers:
    while True:
        try:
            age = int(input(f"Enter the age of {teenager}: "))
            if 16 <= age <= 21:
                print(f"{teenager} is not permitted to watch the movie.")
            else:
                permitted_teenagers.append(teenager)
            break  # Exit the inner loop after successful age input
        except ValueError:
            print("Invalid input. Please enter a valid age (a whole number).")

print("The final list of permitted teenagers:", permitted_teenagers)

"""Exercise 10 : Sandwich Orders
Instructions
Using the list below :

sandwich_orders = ["Tuna sandwich", "Pastrami sandwich", "Avocado sandwich", "Pastrami sandwich", "Egg sandwich", "Chicken sandwich", "Pastrami sandwich"]

The deli has run out of pastrami, use a while loop to remove all occurrences of “Pastrami sandwich” from sandwich_orders.
We need to prepare the orders of the clients:
Create an empty list called finished_sandwiches.
One by one, remove each sandwich from the sandwich_orders while adding them to the finished_sandwiches list.
After all the sandwiches have been made, print a message listing each sandwich that was made, such as:
I made your tuna sandwich
I made your avocado sandwich
I made your egg sandwich
I made your chicken sandwich

"""

sandwich_orders = ["Tuna sandwich", "Pastrami sandwich", "Avocado sandwich", "Pastrami sandwich", "Egg sandwich", "Chicken sandwich", "Pastrami sandwich"]
finished_sandwiches = []

while "Pastrami sandwich" in sandwich_orders:
    sandwich_orders.remove("Pastrami sandwich")

for sandwich in sandwich_orders:
    finished_sandwiches.append(sandwich)
    print(f"I made your {sandwich.lower()}")