# -*- coding: utf-8 -*-
"""mini project 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fySuRKBVAgEllCrAJoi8EkTi0959S9B-

Instructions
The computer choose a random word and mark stars for each letter of each word.
Then the player will guess a letter.
If that letter is in the word(s) then the computer fills the letter in all the correct positions of the word.
If the letter isn’t in the word(s) then add a body part to the gallows (head, body, left arm, right arm, left leg, right leg).
The player will continue guessing letters until they can either solve the word(s) (or phrase) or all six body parts are on the gallows.
The player can’t guess the same letter twice.
"""

import random

def get_word():
  """Returns a random word from a list."""
  words = ["python", "javascript", "programming", "computer", "science"]
  return random.choice(words)

def play_hangman():
  """Plays a game of Hangman."""
  word = get_word()
  word_letters = set(word)  # Letters in the word
  alphabet = set(chr(i) for i in range(ord('a'), ord('z') + 1))
  used_letters = set()  # What the user has guessed

  lives = 6

  # Getting user input
  while len(word_letters) > 0 and lives > 0:
    # Letters used
    print('You have', lives, 'lives left and you have used these letters: ', ' '.join(used_letters))

    # Current word (ie W - R D)
    word_list = [letter if letter in used_letters else '-' for letter in word]
    print('Current word: ', ' '.join(word_list))

    user_letter = input('Guess a letter: ').lower()
    if user_letter in alphabet - used_letters:
      used_letters.add(user_letter)
      if user_letter in word_letters:
        word_letters.remove(user_letter)
        print('')

      else:
        lives = lives - 1  # Takes away a life if wrong
        print('\nYour letter,', user_letter, 'is not in the word.')

    elif user_letter in used_letters:
      print('\nYou have already used that character. Please try again.')

    else:
      print('\nThat is not a valid letter.')

  # Gets here when len(word_letters) == 0 OR lives == 0
  if lives == 0:
    print('You died, sorry. The word was', word)
  else:
    print('You guessed the word', word, '!!')

if __name__ == '__main__':
  play_hangman()