# -*- coding: utf-8 -*-
"""daily challenge

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uvAadswZUDovf5eRmJr1sCV2NygUmh7D

Your Task
Calculate the Required Sample Size:
Imagine the current checkout process has a conversion rate of 5%, and the bakery’s team is confident the new process will boost this to 7%.
Use Python to calculate the required sample size per group (current vs. new checkout process) with an effect size of 0.2, a significance level of 0.05, and a desired power of 0.8.

Analyze the Impact of Effect Size:

The bakery’s head chef, always aiming for perfection, wonders what would happen if the effect size were different. Calculate the required sample size for effect sizes of 0.1, 0.2, 0.3, and 0.4.
Explain how the sample size requirements change as the effect size changes. Why does this happen?

Explain the Relationship:

Imagine you’re explaining this to the bakery’s team in a fun, easy-to-understand way. Why is it so important to balance effect size and sample size when planning an A/B test? Help them understand how this ensures they’re not wasting time or resources and how it helps them confidently make decisions that could increase their sweet sales.
"""

import statsmodels.stats.power as smp

# Current conversion rate
p1 = 0.05

# Desired conversion rate
p2 = 0.07

# Effect size
effect_size = 0.2

# Significance level
alpha = 0.05

# Power
power = 0.8

# Calculate sample size per group
sample_size = smp.tt_ind_solve_power(
    effect_size=effect_size,
    alpha=alpha,
    power=power,
    ratio=1,  # Equal sample size for both groups
    alternative='two-sided'
)

print(f"Required sample size per group: {round(sample_size)}")


# Analyze the Impact of Effect Size:
effect_sizes = [0.1, 0.2, 0.3, 0.4]
for effect_size in effect_sizes:
  sample_size = smp.tt_ind_solve_power(
      effect_size=effect_size,
      alpha=alpha,
      power=power,
      ratio=1,
      alternative='two-sided'
  )
  print(f"Required sample size for effect size {effect_size}: {round(sample_size)}")



# Explain the Relationship
# It's like baking a cake! If you want to see a big difference between two recipes (a large effect size),
# you don't need to bake as many cakes to see that difference. But, if the difference is small (a small effect size),
# you need to bake more cakes (larger sample size) to be sure that the difference isn't just random chance.
#
# Balancing effect size and sample size is important because:
# * If you have a small effect size and a small sample size, you might miss a real difference that exists.
# * If you have a large sample size and a large effect size, you'll quickly be able to see a difference,
#   but you might waste resources testing something that's already obvious.
# * By choosing the right balance, you can ensure that your A/B test gives you reliable results,
#   and you don't waste time and resources testing something that doesn't matter.
# * Ultimately, having a well-designed test with a proper sample size allows you to make confident
#   decisions that could increase your sales and optimize your business.