# -*- coding: utf-8 -*-
"""xp

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ds67Ltj4YrY-GnVV-jL-rmy6_yLjSXLC

Exercise 1 : Hello World
Instructions
Print the following output in one line of code:

Hello world
Hello world
Hello world
Hello world
"""

print('hello world'*4)

"""Exercise 2 : Some Math
Instructions
Write code that calculates the result of: (99^3)*8 (meaning 99 to the power of 3, times 8).


"""

math = (99**3)*8
print(math)

"""Exercise 3 : What is the output ?
Instructions
Predict the output of the following code snippets:

>>> 5 < 3  flase
>>> 3 == 3   true
>>> 3 == "3"  error
>>> "3" > 3   error
>>> "Hello" == "hello"  false

Exercise 4 : Your computer brand
Instructions
Create a variable called computer_brand which value is the brand name of your computer.
Using the computer_brand variable print a sentence that states the following: "I have a <computer_brand> computer".
"""

computer_brand = 'dell'
print(f'I have a {computer_brand} computer')

"""Exercise 5 : Your information
Instructions
Create a variable called name, and set it’s value to your name.
Create a variable called age, and set it’s value to your age.
Create a variable called shoe_size, and set it’s value to your shoe size.
Create a variable called info and set it’s value to an interesting sentence about yourself. The sentence must contain all the variables created in parts 1, 2 and 3.
Have your code print the info message.
Run your code

"""

name='tarek'
age=30
shoe_size=41
info=f'my name is {name} and i am {age} years old and my shoe size is {shoe_size}'
print(info)

""" Exercise 6 : A & B
Instructions
Create two variables, a and b.
Each variable value should be a number.
If a is bigger then b, have your code print Hello World.

"""

a=6
b=4
if a>b:
  print('hello world')

"""Exercise 7 : Odd or Even
Instructions
Write code that asks the user for a number and determines whether this number is odd or even.


"""

user_number=int(input('enter a number'))
if user_number%2==0:
  print(f'{user_number} is even')
else:
  print(f'{user_number} is odd')

"""🌟 Exercise 8 : What’s your name ?
Instructions
Write code that asks the user for their name and determines whether or not you have the same name, print out a funny message based on the outcome.


"""

user_name=input('enter name')
if user_name=='tarek':
  print('hi my clone')
else:
  print('nice to meet you')

""" Exercise 9 : Tall enough to ride a roller coaster
Instructions
Write code that will ask the user for their height in centimeters.
If they are over 145cm print a message that states they are tall enough to ride.
If they are not tall enough print a message that says they need to grow some more to ride.

"""

user_hight=int(input('whats youre hight in cm'))
if user_hight>=145:
  print('you are tall enough')
else:
  print('you need to grow some more')