# -*- coding: utf-8 -*-
"""xp gold

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gUypkQeh6GfLPV6tZ3nqUpnCRW-PmfHM

Exercise 1 : Hello World-I love Python
Instructions
Print the following output in one line of code:

Hello world
Hello world
Hello world
Hello world
I love python
I love python
I love python
I love python
"""

print("Hello world\n"*4+"I love python\n"*4)

"""Exercise 2 : What is the Season ?
Instructions
Ask the user to input a month (1 to 12).
Display the season of the month received :
Spring runs from March (3) to May (5)
Summer runs from June (6) to August (8)
Autumn runs from September (9) to November (11)
Winter runs from December (12) to February (2)

"""

user_month=input('enter a month number (1-12):')
spring=[3,4,5]
summer=[6,7,8]
autumn=[9,10,11]
winter=[12,1,2]
if int(user_month) in spring:
  print('spring')
elif int(user_month) in summer:
  print('summer')
elif int(user_month) in autumn:
  print('autumn')