# -*- coding: utf-8 -*-
"""xp ninja

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15rojymZjlu77xByhHmnX5ZkoC0yojfde

Exercise 1 : Use the terminal
Instructions
Run this command in the terminal to open a python console:
$ python3
Hint: Replace python3 with python for Windows

Read about the PATH variable. Try to explain why you can call python3 if you aren’t in the executable directory.
"""

!python

"""Exercise 2 : Alias
Instructions
Read about alias, and try to open a python console with the command:

$ py
"""

!py

"""Exercise 3 : Outputs
Instructions
Predict the output of the following code snippets:

    >>> 3 <= 3 < 9  true
    >>> 3 == 3 == 3  true
    >>> bool(0)  true
    >>> bool(5 == "5")  error
    >>> bool(4 == 4) == bool("4" == "4")  true
    >>> bool(bool(None))  true
    x = (1 == True)
    y = (1 == False)
    a = True + 4
    b = False + 10

    print("x is", x)  true
    print("y is", y)  false
    print("a:", a)  5
    print("b:", b)  10

Exercise 4 : How many characters in a sentence ?
Instructions
Use python to find out how many characters are in the following text, use a single line of code (beyond the establishment of your my_text variable).

my_text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit,
           sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
           Ut enim ad minim veniam, quis nostrud exercitation ullamco
           laboris nisi ut aliquip ex ea commodo consequat.
           Duis aute irure dolor in reprehenderit in voluptate velit
           esse cillum dolore eu fugiat nulla pariatur.
           Excepteur sint occaecat cupidatat non proident,
           sunt in culpa qui officia deserunt mollit anim id est laborum.
"""

my_text="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore mana aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum"
print(len(my_text))

"""Exercise 5: Longest word without a specific character
Instructions
Keep asking the user to input the longest sentence they can without the character “A”.
Each time a user successfully sets a new longest sentence, print a congratulations message.

"""

def get_longest_word_without_a():
    longest_word = ""
    while True:
        word = input("Enter the longest word without the letter 'a': ")
        if 'a' in word.lower():
            print("Invalid word. The word contains the letter 'a'.")
            continue
        if len(word) > len(longest_word):
            longest_word = word
            print("Congratulations! You've set a new longest word:", longest_word)
        else:
            print("Your word is not longer than the current longest word.")
get_longest_word_without_a()