# -*- coding: utf-8 -*-
"""daily challenge gold

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16gaE-gVIMdRYn4XP9X0dNsX1sLHWJ7NJ

instruction: Information from the userHarder Daily ChallengeNotice : solve this exercise using a lambda function.Ask a user for the following inputs 5 times:Name (string)Age (int)Score (int)Build a list of tuples using these inputs, each tuple should contain a name, age and score.Sort the list by the following priority Name > Age > Score.If the following tuples are given as input to the script:Tom,19,80John,20,90Jony,17,91Jony,17,93Json,21,85Then, the output of the program should be:[('John', '20', '90'), ('Jony', '17', '91'), ('Jony', '17', '93'), ('Json', '21', '85'), ('Tom', '19', '80')]Note : The lambda function will not print but sort
"""

data = []
for _ in range(5):
    name = input("Enter name: ")
    age = input("Enter age: ")
    score = input("Enter score: ")
    data.append((name, age, score))


sorted_data = sorted(data, key=lambda x: (x[0], x[1], x[2]))
sorted_data

print(sorted_data)