# -*- coding: utf-8 -*-
"""daily challenge

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16gaE-gVIMdRYn4XP9X0dNsX1sLHWJ7NJ

Instructions :
The goal is to create a class that represents a simple circle.
A Circle can be defined by either specifying the radius or the diameter.
The user can query the circle for either its radius or diameter.

Other abilities of a Circle instance:

Compute the circle’s area
Print the attributes of the circle - use a dunder method
Be able to add two circles together, and return a new circle with the new radius - use a dunder method
Be able to compare two circles to see which is bigger, and return a Boolean - use a dunder method
Be able to compare two circles and see if there are equal, and return a Boolean- use a dunder method
Be able to put them in a list and sort them
Bonus (not mandatory) : Install the Turtle module, and draw the sorted circles
"""

import math

class Circle:
    def __init__(self, radius=None, diameter=None):
        if radius is not None:
            self.radius = radius
        elif diameter is not None:
            self.radius = diameter / 2
        else:
            raise ValueError("Must specify either radius or diameter")

    @property
    def diameter(self):
        return self.radius * 2

    def area(self):
        return math.pi * self.radius**2

    def __str__(self):
        return f"Circle(radius={self.radius}, diameter={self.diameter})"

    def __repr__(self):
        return self.__str__()

    def __add__(self, other):
        return Circle(radius=self.radius + other.radius)

    def __lt__(self, other):
        return self.radius < other.radius

    def __eq__(self, other):
        return self.radius == other.radius

    def __gt__(self, other):
        return self.radius > other.radius

# Example usage
circle1 = Circle(radius=5)
circle2 = Circle(diameter=10)
circle3 = circle1 + circle2
print(circle1)
print(circle2)
print(circle3)
print(circle1.area())
print(circle1 > circle2)
print(circle1 < circle2)
print(circle1 == circle2)

circles = [Circle(radius=2), Circle(radius=8), Circle(radius=3)]
circles.sort()
print([str(c) for c in circles])