# -*- coding: utf-8 -*-
"""xp gold

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MPxwSZnFcmKKwajCC6pbc3Ly9r6374JW

Exercise 1 : Geometry
Instructions
Write a class called Circle that receives a radius as an argument (default is 1.0).
Write two instance methods to compute perimeter and area.
Write a method that prints the geometrical definition of a circle.
"""

class circle:
  def __init__(self,radius=1.0):
    self.radius=radius
  def perimeter(self):
    return 2*3.14*self.radius
  def area(self):
    return 3.14*self.radius**2
  def print_definition(self):
    print("A circle is the set of all points in a plane that are at a given distance from a given point, the centre.")

"""Exercise 2 : Custom List Class
Instructions
Create a class called MyList, the class should receive a list of letters.
Add a method that returns the reversed list.
Add a method that returns the sorted list.
Bonus : Create a method that generates a second list with the same length as mylist. The list should be constructed with random numbers. (use list comprehension).

"""

import random

class MyList:
  def __init__(self, letters):
    self.letters = letters

  def reversed_list(self):
    return self.letters[::-1]

  def sorted_list(self):
    return sorted(self.letters)

  def generate_random_list(self):
    return [random.randint(1, 100) for _ in range(len(self.letters))]

"""Exercise 3 : Restaurant Menu Manager
Instructions
The purpose of this exercise is to create a restaurant menu. The code will allow a manager to add and delete dishes.

Create a python file called menu_manager.py.

Create a class called MenuManager.

Create a method __init__ that instantiates an attribute called menu. The menu attributes value will be all the current dishes (list of dictionaries). Each dish will be stored in a dictionary where the keys are name, price, spice level and gluten index (which value is a boolean).

Here is a list of the dishes currently on the menu:

    Soup – 10 – B - False
    Hamburger – 15 - A - True
    Salad – 18 - A - False
    French Fries – 5 - C - False
    Beef bourguignon– 25 - B - True

    Meaning: For the spice level:
       • A = not spicy,
       • B = a little spicy,
       • C = very spicy


The dishes provided above should be the value of the menu attribute.

Create a method called add_item(name, price, spice, gluten). This method will add new dishes to the menu.

Create a method called update_item(name, price, spice, gluten). This method checks whether a dish is in the menu, if the dish exists then update it. If not notify the manager that the dish is not in the menu.

Create a method called remove_item(name). This method should check if the dish is in the menu, if the dish exists then delete it and print the updated dictionary. If not notify the manager that the dish is not in the menu.


"""

class MenuManager:
    def __init__(self):
        self.menu = [
            {"name": "Soup", "price": 10, "spice": "B", "gluten": False},
            {"name": "Hamburger", "price": 15, "spice": "A", "gluten": True},
            {"name": "Salad", "price": 18, "spice": "A", "gluten": False},
            {"name": "French Fries", "price": 5, "spice": "C", "gluten": False},
            {"name": "Beef bourguignon", "price": 25, "spice": "B", "gluten": True},
        ]

    def add_item(self, name, price, spice, gluten):
        new_dish = {"name": name, "price": price, "spice": spice, "gluten": gluten}
        self.menu.append(new_dish)
        print(f"Dish '{name}' added to the menu.")

    def update_item(self, name, price, spice, gluten):
        for dish in self.menu:
            if dish["name"] == name:
                dish["price"] = price
                dish["spice"] = spice
                dish["gluten"] = gluten
                print(f"Dish '{name}' updated successfully.")
                return
        print(f"Dish '{name}' not found in the menu.")

    def remove_item(self, name):
        for dish in self.menu:
            if dish["name"] == name:
                self.menu.remove(dish)
                print(f"Dish '{name}' removed from the menu.")
                print("Updated menu:", self.menu)
                return
        print(f"Dish '{name}' not found in the menu.")


# Example usage:
menu = MenuManager()

# Add a new dish
menu.add_item("Pasta", 12, "A", True)

# Update an existing dish
menu.update_item("Soup", 12, "A", False)

# Remove a dish
menu.remove_item("Hamburger")