# -*- coding: utf-8 -*-
"""xp ninja

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MPxwSZnFcmKKwajCC6pbc3Ly9r6374JW

Exercise 1 : Call History
Instructions
Create a class called Phone. This class takes a parameter called phone_number. When instantiating an object create an attribute called call_history which value is an empty list.

Add a method called call that takes both self and other_phone (i.e another Phone object) as parameters. The method should print a string stating who called who, and add this string to the phone’s call_history.

Add a method called show_call_history. This method should print the call_history.

Add another attribute called messages to your __init__() method which value is an empty list.

Create a method called send_message which is similar to the call method. Each message should be saved as a dictionary with the following keys:
to : the number of another Phone object
from : your phone number (also a Phone object)
content

Create the following methods: show_outgoing_messages(self), show_incoming_messages(self), show_messages_from(self)

Test your code !!!
"""

class Phone:
    def __init__(self, phone_number):
        self.phone_number = phone_number
        self.call_history = []
        self.messages = []

    def call(self, other_phone):
        call_log = f"{self.phone_number} called {other_phone.phone_number}"
        print(call_log)
        self.call_history.append(call_log)

    def show_call_history(self):
        print(self.call_history)

    def send_message(self, other_phone, content):
        message = {"to": other_phone.phone_number, "content": content}
        self.messages.append(message)

    def show_outgoing_messages(self):
        print([msg for msg in self.messages])

    def show_incoming_messages(self):

        pass

    def show_messages_from(self, other_phone):

        pass

# Example usage:
phone1 = Phone("123-456-7890")
phone2 = Phone("987-654-3210")

phone1.call(phone2)
phone2.call(phone1)

phone1.show_call_history()

phone1.send_message(phone2, "Hello from phone 1")
phone2.send_message(phone1, "Hello from phone 2")

phone1.show_outgoing_messages()