# -*- coding: utf-8 -*-
"""mini project 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y0-qaOFMS1UfUazq9AYv5myey7sVMesO

Anagram checker
We will create a program that will ask the user for a word.
It will check if the word is a valid English word, and then find all possible anagrams for that word.



Instructions
First Download this text file

Create a new file called anagram_checker.py which contains a class called AnagramChecker.

The class should have the following methods:
__init__ - should load the word list file (text file) into a variable, so that it can be searched later on in the code.
is_valid_word(word) – should check if the given word (ie. the word of the user) is a valid word.

get_anagrams(word) – should find all anagrams for the given word. (eg. if word of the user is ‘meat’, the function should return a list containing [“mate”, “tame”, “team”].)

Hint: you might want to create a separate method called is_anagram(word1, word2), that will compare 2 words and return True if they contain the same letters (but not in the same order), and False if not.

Note: None of the methods in the class should print anything.

Now create another Python file, called anagrams.py. This will contain all the UI (user interface) functionality of your program, and will rely on AnagramChecker for the anagram-related logic.

It should do the following:
Show a menu, offering the user to input a word or exit. Keep showing the menu until the user chooses to exit.

If the user chooses to input a word, it must be accepted from the user’s keyboard input, and then be validated:
Only a single word is allowed. If the user typed more than one word, show an error message. (Hint: how do we know how many words were typed?)
Only alphabetic characters are allowed. No numbers or special characters.
Whitespace should be removed from the start and end of the user’s input.

Once your code has decided that the user’s input is valid, it should find out the following:
All possible anagrams to the user’s word.
Create an AnagramChecker instance and apply it to the steps created above.
Display the information about the word in a user-friendly, nicely-formatted message such as:


YOUR WORD :”MEAT”
this is a valid English word.
Anagrams for your word: mate, tame, team.
"""

class AnagramChecker:
    def __init__(self, word_list_file="sowpods.txt"):
        with open(word_list_file, "r") as f:
            self.word_list = [word.strip().lower() for word in f]

    def is_valid_word(self, word):
        return word.lower() in self.word_list

    def get_anagrams(self, word):
        word = word.lower()
        anagrams = []
        for w in self.word_list:
            if sorted(w) == sorted(word) and w != word:
                anagrams.append(w)
        return anagrams


def main():
    anagram_checker = AnagramChecker()

    while True:
        print("\nMenu:")
        print("1. Enter a word")
        print("2. Exit")
        choice = input("Enter your choice: ")

        if choice == "1":
            word = input("Enter a word: ")
            word = word.strip()

            if not word.isalpha():
                print("Error: Only alphabetic characters are allowed.")
                continue
            if " " in word:
                print("Error: Only a single word is allowed.")
                continue

            if anagram_checker.is_valid_word(word):
                anagrams = anagram_checker.get_anagrams(word)
                print(f"\nYOUR WORD: '{word.upper()}'")
                print("This is a valid English word.")
                if anagrams:
                    print("Anagrams for your word:", ", ".join(anagrams))
                else:
                    print("No anagrams found for your word.")
            else:
                print(f"\nYOUR WORD: '{word.upper()}'")
                print("This is not a valid English word.")

        elif choice == "2":
            break
        else:
            print("Invalid choice. Please try again.")


if __name__ == "__main__":
    main()